import fs from "fs";
import path from "path";
import { $ } from "bun";

const getSubdirectories = (dir) => {
  return fs.readdirSync(dir).filter((file) => {
    const fullPath = path.join(dir, file);
    return (
      fs.statSync(fullPath).isDirectory() &&
      !file.startsWith(".") &&
      file !== "node_modules" &&
      file !== "dist"
    );
  });
};

const createBanner = (themePath) => {
  const theme = JSON.parse(fs.readFileSync(themePath, "utf-8"));

  let banner = `// ==UserScript==
// @name            ${theme.name}
// @description     ${theme.description}
// @author          ${theme.author}
// @version         ${theme.version}
// @lastUpdated     ${theme.updatedAt}
`;

  if (theme.ignoreCache !== false) {
    banner += `// @ignorecache\n`;
  }

  const standardKeys = [
    "id",
    "name",
    "description",
    "author",
    "version",
    "updatedAt",
    "tags",
    "fork",
    "preferences",
    "style",
    "scripts",
    "readme",
    "image",
    "createdAt",
    "ignoreCache",
  ];

  for (const key in theme) {
    if (!standardKeys.includes(key)) {
      const value = theme[key];
      if (Array.isArray(value)) {
        value.forEach((item) => {
          banner += `// @${key.padEnd(15)} ${item}\n`;
        });
      } else if (typeof value === "boolean") {
        if (value) banner += `// @${key}\n`;
      } else {
        banner += `// @${key.padEnd(15)} ${value}\n`;
      }
    }
  }

  banner += `// ==/UserScript==

// This file was automatically generated. Do not edit this file directly.
// Any changes made here will be overwritten.
// To make changes, please edit the source files in the repository:
// https://github.com/BibekBhusal0/zen-custom-js

`;

  return banner;
};

async function buildMod(themePath, entryFile, theme, isWatch = false) {
  const banner = createBanner(themePath);

  const runBuild = async (options, label) => {
    try {
      const result = await Bun.build(options);
      if (!result.success) {
        for (const log of result.logs) console.error(`[${label}]`, log);
        throw new Error(`Build failed: ${label}`);
      }
      console.log(`Built ${label}`);
    } catch (err) {
      if (err instanceof AggregateError) {
        for (const sub of err.errors) console.error(`[${label}]`, sub?.message ?? sub);
        throw new Error(`Build failed: ${label}`);
      }
      throw err;
    }
  };

  if (theme.id === "browse-bot") {
    const externalPackages = [
      "@ai-sdk/*",
      "ai",
      "zod",
      "ollama-ai-provider-v2",
      "*/vercel-ai-sdk.uc.mjs",
    ];

    await runBuild(
      {
        entrypoints: [entryFile],
        outdir: "./dist",
        format: "esm",
        target: "browser",
        naming: "browse-bot.uc.mjs",
        banner,
        minify: { syntax: true },
        external: externalPackages,
      },
      "browse-bot.uc.mjs"
    );

    await runBuild(
      {
        entrypoints: ["./findbar-ai/vercel-ai-sdk.uc.mjs"],
        outdir: "./dist",
        format: "esm",
        target: "browser",
        naming: "vercel-ai-sdk.uc.mjs",
        minify: { syntax: true },
      },
      "vercel-ai-sdk.uc.mjs"
    );

    if (isWatch) {
      const mainWatch = $`bun build ${entryFile} --outdir ./dist --format esm --target browser --entry-naming browse-bot.uc.mjs --banner "${banner}" --minify-syntax --external "@ai-sdk/*" --external ai --external zod --external ollama-ai-provider-v2 --external "*/vercel-ai-sdk.uc.mjs" --watch`;
      const vendorWatch = $`bun build ./findbar-ai/vercel-ai-sdk.uc.mjs --outdir ./dist --format esm --target browser --entry-naming vercel-ai-sdk.uc.mjs --minify-syntax --watch`;
      await Promise.all([mainWatch, vendorWatch]);
    }

    return;
  }

  await runBuild(
    {
      entrypoints: [entryFile],
      outdir: "./dist",
      format: "iife",
      target: "browser",
      naming: `${theme.id}.uc.js`,
      banner,
      minify: { syntax: true },
    },
    `${theme.id}.uc.js`
  );

  if (isWatch) {
    await $`bun build ${entryFile} --outdir ./dist --format iife --target browser --entry-naming ${theme.id}.uc.js --banner "${banner}" --minify-syntax --watch`;
  }
}

async function build() {
  const target = process.env.TARGET;
  const isWatch = process.argv.includes("--watch");

  if (isWatch && !target) {
    const browseBotTheme = JSON.parse(await Bun.file("findbar-ai/theme.json").text());
    const browseBotEntry = "findbar-ai/index.js";

    await buildMod("findbar-ai/theme.json", browseBotEntry, browseBotTheme, true);
    return;
  }

  const mods = getSubdirectories(process.cwd());
  let modsToBuild = mods;
  if (target) {
    const normalizedTarget = target.replace(/-/g, "");
    const modsWithThemes = await Promise.all(
      mods.map(async (dir) => {
        const themePath = path.join(dir, "theme.json");
        if (!fs.existsSync(themePath)) return { dir, include: false };

        try {
          const theme = JSON.parse(await Bun.file(themePath).text());
          const normalizedThemeId = theme.id.replace(/-/g, "");
          return { dir, include: normalizedThemeId.includes(normalizedTarget) };
        } catch {
          return { dir, include: false };
        }
      })
    );
    modsToBuild = modsWithThemes.filter((m) => m.include).map((m) => m.dir);
  }

  let built = 0;
  for (const dir of modsToBuild) {
    const themePath = path.join(dir, "theme.json");
    const entryFile = path.join(dir, "index.js");

    if (!fs.existsSync(themePath) || !fs.existsSync(entryFile)) {
      console.warn(`Skipped ${dir}: missing theme.json or index.js`);
      continue;
    }

    const theme = JSON.parse(await Bun.file(themePath).text());
    if (!theme.scripts) {
      console.warn(`Skipped ${dir}: no scripts key in theme.json`);
      continue;
    }
    await buildMod(themePath, entryFile, theme, isWatch);
    built++;
  }

  if (target && built === 0) {
    throw new Error(`No mods matched TARGET="${target}"`);
  }
  console.log(`Done: built ${built} mod(s).`);
}

build().catch((err) => {
  console.error(err?.message ?? err);
  process.exit(1);
});
